name: yoloworld
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - albucore==0.0.24
      - albumentations==1.1.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - certifi==2022.12.7
      - cffi==2.0.0
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cmake==3.25.0
      - colorama==0.4.6
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==46.0.2
      - cycler==0.12.1
      - defusedxml==0.7.1
      - eval-type-backport==0.2.2
      - filelock==3.14.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.4
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lit==15.0.7
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mmcv==2.0.1
      - mmdet==3.3.0
      - mmengine==0.10.6
      - mmyolo==0.6.0
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.8.0.76
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.4.0
      - prettytable==3.16.0
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.3
      - qudida==0.0.4
      - regex==2025.9.18
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.6.2
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - simsimd==6.5.3
      - six==1.17.0
      - stringzilla==4.1.0
      - supervision==0.19.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==0.6.13
      - tokenizers==0.13.3
      - tomli==2.2.1
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tqdm==4.65.2
      - transformers==4.33.0
      - triton==2.0.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - wcwidth==0.2.14
      - yapf==0.43.0
      - yolo-world==0.1.0
      - zipp==3.23.0
prefix: /home/agipml/21d070064/miniconda3/envs/yoloworld
